### ISSUE TITLE
KeyError: 'dlink'

### ISSUE THREAD

**Issue by xuesongbj** [tychxn/baidu-wangpan-parse#8]
Exception: 'dlink'
Traceback (most recent call last):
  File "baidu_wangpan_parse.py", line 219, in <module>
    main(options)
  File "baidu_wangpan_parse.py", line 209, in main
    link = wangpan.get_download_link()
  File "baidu_wangpan_parse.py", line 190, in get_download_link
    return js['dlink'] if self.is_folder else js['list'][0]['dlink']
KeyError: 'dlink'

**Comment by tychxn** [comment]
请问是否下载的是文件夹，如果是的话需要加上`-f`参数
类似：```$ python baidu_wangpan_parse.py -f https://pan.baidu.com/s/1htWjWk0 5ykw```
